# fly.toml app configuration file generated for full-stack-open-pokedex-zhangtdavid on 2025-10-30T11:50:22-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-zhangtdavid'
primary_region = 'sjc'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js" # add thi

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
