name: Test Workflow

on: push

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: skip_condition
        if: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: echo "no skip"
      - name: no_skip_condition
        if: ${{ !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: echo "yes skip"